### ISSUE TITLE
develop - No module named X

### ISSUE THREAD

**Issue by alejandrox1** [TACC/agavepy#56]
Currently, using `TACC/agavepy` from anywhere besides the repo will result in an error message like this:
```python
Python 3.6.6 (default, Sep  5 2018, 03:40:52) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from agavepy.agave import Agave
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/agavepy-0.7.1-py3.6.egg/agavepy/agave.py", line 22, in <module>
    from .tenants import tenant_list
ModuleNotFoundError: No module named 'agavepy.tenants'
>>> 
```

The problem with this is that the installation via `setup.py` requires an explicit mention of all submodules withing the package.
To fix this use the following code in `setup.py`:
```python
from setuptools import setup, find_packages                                     
                                                                                
setup(                                                                          
    ...
    packages=find_packages(),
    ....                                                   
)
```

Will postpone this fix as the vast majority of `TACC/agavepy` seems to make use of the submodule `swaggerpy` and this is used in a non-conventional way.

**Comment by alejandrox1** [comment]
Until there is aplan to do something about the swaggerpy module, see #57 for a solution.
