### ISSUE TITLE
ag.apps.list(publicOnly='false') returns only public apps

### ISSUE THREAD

**Issue by mrhanlon** [TACC/agavepy#6]
It appears that the `publicOnly` parameter for `apps.list` always returns only public apps if the argument is present, regardless of the value. Similarly, the `privateOnly` parameter always returns private apps when present. It is easy enough to work around this, so not a high priority.

```bash
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from agavepy.agave import Agave
>>> ag = Agave(api_server='https://agave.designsafe-ci.org', api_key='***', api_secret='***', username='***', password='***')
>>> ag.apps.list()
[{u'name': u'opensees', u'lastModified': datetime.datetime(2015, 12, 22, 8, 52, 35, tzinfo=tzoffset(None, -21600)), u'isPublic': True, u'label': u'OpenSees', u'executionSystem': u'designsafe.exec.stampede', u'version': u'2.4.4.5804', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/opensees-2.4.4.5804u1'}}, u'shortDescription': u'OpenSees is a software framework for simulating the seismic response of structural and geotechnical systems.', u'id': u'opensees-2.4.4.5804u1', u'revision': 1}, {u'name': u'opensees', u'lastModified': datetime.datetime(2015, 12, 18, 15, 2, 27, tzinfo=tzoffset(None, -21600)), u'isPublic': False, u'label': u'OpenSees', u'executionSystem': u'designsafe.exec.stampede', u'version': u'2.4.4.5804', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/opensees-2.4.4.5804'}}, u'shortDescription': u'OpenSees is a software framework for simulating the seismic response of structural and geotechnical systems.', u'id': u'opensees-2.4.4.5804', u'revision': 3}, {u'name': u'fork-runner', u'lastModified': datetime.datetime(2015, 12, 17, 23, 20, 54, tzinfo=tzoffset(None, -21600)), u'isPublic': False, u'label': u'Fork a command at a shell', u'executionSystem': u'stampede-mrojas', u'version': u'0.1.0', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/fork-runner-0.1.0'}}, u'shortDescription': u'This will fork whatever command you give in the command parameter', u'id': u'fork-runner-0.1.0', u'revision': 1}, {u'name': u'opensees-fork', u'lastModified': datetime.datetime(2015, 12, 16, 16, 22, 16, tzinfo=tzoffset(None, -21600)), u'isPublic': False, u'label': u'OpenSees', u'executionSystem': u'designsafe.exec.stampede', u'version': u'2.4.4.5804', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/opensees-fork-2.4.4.5804'}}, u'shortDescription': u'OpenSees is a software framework for simulating the seismic response of structural and geotechnical systems.', u'id': u'opensees-fork-2.4.4.5804', u'revision': 3}]
>>> ag.apps.list(publicOnly='true')
[{u'name': u'opensees', u'lastModified': datetime.datetime(2015, 12, 22, 8, 52, 35, tzinfo=tzoffset(None, -21600)), u'isPublic': True, u'label': u'OpenSees', u'executionSystem': u'designsafe.exec.stampede', u'version': u'2.4.4.5804', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/opensees-2.4.4.5804u1'}}, u'shortDescription': u'OpenSees is a software framework for simulating the seismic response of structural and geotechnical systems.', u'id': u'opensees-2.4.4.5804u1', u'revision': 1}]
>>> ag.apps.list(publicOnly='false')
[{u'name': u'opensees', u'lastModified': datetime.datetime(2015, 12, 22, 8, 52, 35, tzinfo=tzoffset(None, -21600)), u'isPublic': True, u'label': u'OpenSees', u'executionSystem': u'designsafe.exec.stampede', u'version': u'2.4.4.5804', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/opensees-2.4.4.5804u1'}}, u'shortDescription': u'OpenSees is a software framework for simulating the seismic response of structural and geotechnical systems.', u'id': u'opensees-2.4.4.5804u1', u'revision': 1}]
>>> ag.apps.list(publicOnly='bar')
[{u'name': u'opensees', u'lastModified': datetime.datetime(2015, 12, 22, 8, 52, 35, tzinfo=tzoffset(None, -21600)), u'isPublic': True, u'label': u'OpenSees', u'executionSystem': u'designsafe.exec.stampede', u'version': u'2.4.4.5804', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/opensees-2.4.4.5804u1'}}, u'shortDescription': u'OpenSees is a software framework for simulating the seismic response of structural and geotechnical systems.', u'id': u'opensees-2.4.4.5804u1', u'revision': 1}]
>>>
>>> ag.apps.list(privateOnly='true')
[{u'name': u'opensees', u'lastModified': datetime.datetime(2015, 12, 18, 15, 2, 27, tzinfo=tzoffset(None, -21600)), u'isPublic': False, u'label': u'OpenSees', u'executionSystem': u'designsafe.exec.stampede', u'version': u'2.4.4.5804', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/opensees-2.4.4.5804'}}, u'shortDescription': u'OpenSees is a software framework for simulating the seismic response of structural and geotechnical systems.', u'id': u'opensees-2.4.4.5804', u'revision': 3}, {u'name': u'fork-runner', u'lastModified': datetime.datetime(2015, 12, 17, 23, 20, 54, tzinfo=tzoffset(None, -21600)), u'isPublic': False, u'label': u'Fork a command at a shell', u'executionSystem': u'stampede-mrojas', u'version': u'0.1.0', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/fork-runner-0.1.0'}}, u'shortDescription': u'This will fork whatever command you give in the command parameter', u'id': u'fork-runner-0.1.0', u'revision': 1}, {u'name': u'opensees-fork', u'lastModified': datetime.datetime(2015, 12, 16, 16, 22, 16, tzinfo=tzoffset(None, -21600)), u'isPublic': False, u'label': u'OpenSees', u'executionSystem': u'designsafe.exec.stampede', u'version': u'2.4.4.5804', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/opensees-fork-2.4.4.5804'}}, u'shortDescription': u'OpenSees is a software framework for simulating the seismic response of structural and geotechnical systems.', u'id': u'opensees-fork-2.4.4.5804', u'revision': 3}]
>>> ag.apps.list(privateOnly='false')
[{u'name': u'opensees', u'lastModified': datetime.datetime(2015, 12, 18, 15, 2, 27, tzinfo=tzoffset(None, -21600)), u'isPublic': False, u'label': u'OpenSees', u'executionSystem': u'designsafe.exec.stampede', u'version': u'2.4.4.5804', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/opensees-2.4.4.5804'}}, u'shortDescription': u'OpenSees is a software framework for simulating the seismic response of structural and geotechnical systems.', u'id': u'opensees-2.4.4.5804', u'revision': 3}, {u'name': u'fork-runner', u'lastModified': datetime.datetime(2015, 12, 17, 23, 20, 54, tzinfo=tzoffset(None, -21600)), u'isPublic': False, u'label': u'Fork a command at a shell', u'executionSystem': u'stampede-mrojas', u'version': u'0.1.0', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/fork-runner-0.1.0'}}, u'shortDescription': u'This will fork whatever command you give in the command parameter', u'id': u'fork-runner-0.1.0', u'revision': 1}, {u'name': u'opensees-fork', u'lastModified': datetime.datetime(2015, 12, 16, 16, 22, 16, tzinfo=tzoffset(None, -21600)), u'isPublic': False, u'label': u'OpenSees', u'executionSystem': u'designsafe.exec.stampede', u'version': u'2.4.4.5804', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/opensees-fork-2.4.4.5804'}}, u'shortDescription': u'OpenSees is a software framework for simulating the seismic response of structural and geotechnical systems.', u'id': u'opensees-fork-2.4.4.5804', u'revision': 3}]
>>> ag.apps.list(privateOnly='bar')
[{u'name': u'opensees', u'lastModified': datetime.datetime(2015, 12, 18, 15, 2, 27, tzinfo=tzoffset(None, -21600)), u'isPublic': False, u'label': u'OpenSees', u'executionSystem': u'designsafe.exec.stampede', u'version': u'2.4.4.5804', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/opensees-2.4.4.5804'}}, u'shortDescription': u'OpenSees is a software framework for simulating the seismic response of structural and geotechnical systems.', u'id': u'opensees-2.4.4.5804', u'revision': 3}, {u'name': u'fork-runner', u'lastModified': datetime.datetime(2015, 12, 17, 23, 20, 54, tzinfo=tzoffset(None, -21600)), u'isPublic': False, u'label': u'Fork a command at a shell', u'executionSystem': u'stampede-mrojas', u'version': u'0.1.0', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/fork-runner-0.1.0'}}, u'shortDescription': u'This will fork whatever command you give in the command parameter', u'id': u'fork-runner-0.1.0', u'revision': 1}, {u'name': u'opensees-fork', u'lastModified': datetime.datetime(2015, 12, 16, 16, 22, 16, tzinfo=tzoffset(None, -21600)), u'isPublic': False, u'label': u'OpenSees', u'executionSystem': u'designsafe.exec.stampede', u'version': u'2.4.4.5804', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/opensees-fork-2.4.4.5804'}}, u'shortDescription': u'OpenSees is a software framework for simulating the seismic response of structural and geotechnical systems.', u'id': u'opensees-fork-2.4.4.5804', u'revision': 3}]
>>>
```

**Comment by waltermoreira** [comment]
Pinging @joestubbs in this, because it may be related to some discrepancies between the swagger resources file included in agavepy and the real stuff returned by agave.  Just guessing...

**Comment by waltermoreira** [comment]
Also, I think it should be `publicOnly=False`, otherwise `'False' == True`.

**Comment by mrhanlon** [comment]
Yes, I tried passing boolean values and got a different error:

```
>>> ag.apps.list(publicOnly=True)
[{u'name': u'opensees', u'lastModified': datetime.datetime(2015, 12, 22, 8, 52, 35, tzinfo=tzoffset(None, -21600)), u'isPublic': True, u'label': u'OpenSees', u'executionSystem': u'designsafe.exec.stampede', u'version': u'2.4.4.5804', u'_links': {u'self': {u'href': u'https://agave.designsafe-ci.org/apps/v2/opensees-2.4.4.5804u1'}}, u'shortDescription': u'OpenSees is a software framework for simulating the seismic response of structural and geotechnical systems.', u'id': u'opensees-2.4.4.5804u1', u'revision': 1}]
>>> ag.apps.list(publicOnly=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/agavepy/agave.py", line 339, in __call__
    resp = with_refresh(self.client, operation)
  File "/usr/local/lib/python2.7/dist-packages/agavepy/agave.py", line 71, in with_refresh
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/agavepy/agave.py", line 335, in operation
    response = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/agavepy/swaggerpy/client.py", line 105, in __call__
    (self.json['nickname'], kwargs.keys()))
TypeError: 'list' does not have parameters ['publicOnly']
>>>
```

**Comment by joestubbs** [comment]
Yes, this has to do with erroneous values in the swagger definition files. I am in agavepy working on some changes to allow persisting clients, so I will fix these too.

**Comment by joestubbs** [comment]
There was an additional issue in the swaggerpy core causing boolean params to not be processed correctly.

The test suite is broken yet again but manual testing seems to confirm the fixes in https://github.com/TACC/agavepy/commit/5642e6bf073f8e051ceeda807400a9c46aec6143 and https://github.com/TACC/agavepy/commit/7068f9fc7c913e4b45a46b35c22269c49ebe3c5f

**Comment by joestubbs** [comment]
Fixed.
